
services:
    dashboard:
        build:
            context: ./Dashboard
        # volumes :
        #     -   ./Dashboard:/app
        ports:
            - ${DashBoard_PORT}:80
        networks:
            - DashboardNetwork
        environment:
            PublicUrl: ${PublicUrlForTelegramBot}
            ASPNETCORE_URLS: "http://+:80"


    telegrambot:
        build:
            context: ./TelegramBot
        depends_on :
            - serviceapi
        # volumes :
        #     - ./TelegramBot:/app
        ports:
            - ${TelegramBot_PORT}:80
        environment:
            PublicUrl: ${PublicUrlForTelegramBot}
            ASPNETCORE_URLS: "http://+:80"
        networks:
            - BotNetwork
    
    serviceapi:
        build:
            context: ./ServiceApi
        depends_on:
            - db
        environment:
             MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
             ASPNETCORE_URLS: "http://+:80"
        # volumes :
        #      - ./ServiceApi:/app
        networks:
            - DbNetwork
            - ServiceApiNetwork

    db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        restart: always
        environment:
            MSSQL_SA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            ACCEPT_EULA: Y
            MSSQL_PID: Developer
        networks:
            - DbNetwork


    vibeservice:
        build:
            context: ./Nginx
        ports:
            - 8443:80
        # volumes:
        # - ./nginx.conf:/etc/nginx/nginx.conf:ro
        networks:
            - ServiceApiNetwork
            - BotNetwork
            - DashboardNetwork
            

networks:
  DbNetwork:
  ServiceApiNetwork:
  DashboardNetwork:
  BotNetwork:

  


                
        