apiVersion: v1
kind: Service
metadata:
  name: vibeservice
spec:
  type: NodePort
  selector:
    app: vibeservice
  ports:
    - protocol: TCP
      port: 80            # порт сервісу всередині кластера
      targetPort: 80      # порт контейнера
      nodePort: 30002     # зовнішній порт на Minikube (будь-який у діапазоні 30000–32767)