apiVersion: apps/v1
kind: Deployment
metadata:
    name: vibeservice
spec:
    replicas: 1
    selector:
        matchLabels:
            app: vibeservice
    template:
        metadata:
            labels:
                app: vibeservice
        spec:
            containers:
             -  name: nginx
                image: iakol/dokertestvibeservice:latest
                ports: 
                -   containerPort: 80
                volumeMounts: 
                -   name: nginx-config
                    mountPath: /etc/nginx/nginx.conf
                    subPath: nginx.conf

            volumes:
            -   name: nginx-config
                configMap:
                    name: nginx-config
