apiVersion: v1
kind: Service
metadata:
  name: serviceapi
spec:
  type: ClusterIP
  selector:
    app: serviceapi
  ports:
    - protocol: TCP
      port: 80            # порт сервісу всередині кластера
      targetPort: 80      # порт контейнера
