apiVersion: apps/v1
kind: Deployment
metadata:
    name: serviceapi
spec:
    replicas: 1
    selector:
        matchLabels:
            app: serviceapi
    template:
        metadata:
            labels:
                app: serviceapi
        spec:
            containers:
             -  name: serviceapi
                image: iakol/dokertestserviceapi:1
                ports: 
                -   containerPort: 80
                env:
                  - name: MYSQL_ROOT_PASSWORD
                    value: "231Dima231"
                  - name: ASPNETCORE_URLS
                    value: "http://+:80"