apiVersion: apps/v1
kind: Deployment
metadata:
    name: telegrambot
spec:
    replicas: 1
    selector:
        matchLabels:
            app: telegrambot
    template:
        metadata:
            labels:
                app: telegrambot
        spec:
            containers:
             -  name: telegrambot
                image: iakol/dokertesttelegrambot:1
                ports: 
                -   containerPort: 80
                env:
                  - name: PublicUrl
                    value: "https://962080b8ead7.ngrok-free.app"
                  - name: ASPNETCORE_URLS
                    value: "http://+:80"